### ISSUE TITLE
target does not exist

### ISSUE THREAD

**Issue by sh1va73** [Taguar258/Raven-Storm#17] opened 2019-11-13 18:02 UTC
I try to get my laptop offline but when i set IP of my laptop and i do Run then it says: target does not exist. But the target set is correct.
When I try my NAS then I get message Success! , but the NAS did not go offline.

**Comment by Taguar258** [comment] 2019-11-13 18:12
Dear sh1va73,
I guess you probably used the TCP mode.
The problem with this mode is that it needs to run on (an) existing port(s).
In your case, I would recommend trying to use the pod method:

Run the script in sudo mode and specify the target using "pod target {ip}"(in Raven-Storm)(You can also do a LAN scan using "lan scan").
You will find the pod help by entering "help".
Use "pod run" to hopefully successfully boot your laptop offline.

Ps: It worked on the NAS because port 80 is opened. (proof: have a look at (enter: "values") or do a port scan on the NAS enter:("port I {IP}"))

Thank you and have a nice day.
In case you still face the problem feel free to ask.

**Comment by sh1va73** [comment] 2019-11-13 18:22
Thanks for your feedback! lan scan is working fine but when I do a pod run on a pod target then I get this:
Running...
sh: 1: [[: not found
I am in sudo mode.

**Comment by Taguar258** [comment] 2019-11-13 18:35
I am going to have a look if it works on my pc.
May I ask what os you use?

**Comment by sh1va73** [comment] 2019-11-13 18:39
> May I ask what os you use?
 I am on latest version of Kali.

**Comment by Taguar258** [comment] 2019-11-13 18:50
I see, the problem is because of the different os I am using.
I spot the problem and I am going to do research about Kali related to Raven-Storm and update the script as soon as possible.

I tested Raven-Storm on a Mac, even though I prefer Kali. (Need to reinstall Kali)

**Comment by sh1va73** [comment] 2019-11-13 20:13
Thanks for your reply! Looking forward for the update. Right now I was just testing on Ubuntu 18.0.4 and here I also have the same issue.

**Comment by Taguar258** [comment] 2019-11-13 21:29
Thank you, I think I fixed it for now.
Not quite the way I would want it to, but it will be completely like the mac version in future versions,
but for now it should work in a completely stable state.

The mac version just verbose a request info form the target, so nothing too important.

I will leave this issue open, so  in case you would face any issues again you would be able to tell me easily.

Feel free to update now.

**Comment by Taguar258** [comment] 2019-11-13 21:50
I am sorry for the delay you need to wait.

**Comment by sh1va73** [comment] 2019-11-13 21:59
Thanks so much for the quick update! I did a quick testing and the errors are gone now.
But the device did no go offline. I maybe did do something wrong, I will do some more testing tomorrow and keep you posted.

**Comment by sh1va73** [comment] 2019-11-13 22:03
This is correct, right?
> pod target 192.168.0.1
> pod run

This should bring my device down?

**Comment by Taguar258** [comment] 2019-11-13 22:14
Exactly, that should be all right, but those problems could be caused by the update, maybe the errors are hidden instead of fixed, my bad - Need to recheck that.
Otherwise everything should work properly like in my previous version tests(not on kali).

I will check that and first of try making the pod more user-friendly in error cases and also checking if it is an os complication or a programming mistake of mine and make it globally working on every unix os.

**Comment by sh1va73** [comment] 2019-11-14 08:37
I tested again. No errors but I can not get the devices offline.
Do I need to set a port with pod?

**Comment by Taguar258** [comment] 2019-11-14 12:29
Hello,

Did you get a reply this time saying something like mode sudo/normal(after the update), because it needs to be replying with "mode sudo" to work properly?

How did you use sudo, using sudo or using su?

**Comment by sh1va73** [comment] 2019-11-14 12:39
In Ubuntu I did:

> sudo python2 rs.pyo
> pod target IP
> pod size
> pod threads
> pod run

Then the tool confirms:

Running...
Sudo mode.

(on Kali I am already logged in as root)

**Comment by Taguar258** [comment] 2019-11-14 12:41
I see, I will make an update for you to verbose important informations which might help finding the issue.
I will inform you as soon as it is published.

Thank you.

**Comment by Taguar258** [comment] 2019-11-14 14:38
I added some verbose,
If you do not mind could you update and try the same using:
`sudo python2 rs.py '!-sh1va73'`

It should print out some verbose in case there are errors.

**Comment by sh1va73** [comment] 2019-11-14 14:53
Thanks for the quick update. I was eager to test again.
Hereby the result:
Running...
[Enter ctrl + z to stop the attack]
Sudo mode.
sh1va73 mode.
PING 192.148.0.8 (192.148.0.8) 65500(65528) bytes of data.
....................................................................................................................................................................

But the device is not going offline.

**Comment by Taguar258** [comment] 2019-11-14 15:47
Perfect, as we should now know everything should be all right.
So just try using higher threads and 65500 kB size.

**Comment by sh1va73** [comment] 2019-11-14 16:01
I already have tried what you suggested but can not get the NAS down with pod mode. Maybe it is build against stress tests.
I will try again with TCP mode and keep you posted.

**Comment by sh1va73** [comment] 2019-11-14 16:04
How setting 2 MB or more?

**Comment by Taguar258** [comment] 2019-11-14 16:12
I guess the NAS(as you said) is just ICMP flood secured.

Personally I got my NAS down using TCP 200 threads and 2mb.

You could also try it with ups flood, just enter `method`.

**Comment by sh1va73** [comment] 2019-11-14 16:26
I am playing around now and testing.
When trying TCP method I get a lot of: Target not exist.
But target is set correct, it is same from lan-scan.

**Comment by sh1va73** [comment] 2019-11-14 16:48
I found out the NAS has DOS protection enabled. I will try tomorrow again without this setting activated. Also I will try this tool on my phone as well. Keep you posted.

**Comment by Taguar258** [comment] 2019-11-14 16:51
Thank you for keeping me updated.

**Comment by sh1va73** [comment] 2019-11-14 17:01
I accidentally clicked closed :)

**Comment by Taguar258** [comment] 2019-11-14 17:21
No problem. ^^

**Comment by sh1va73** [comment] 2019-11-14 17:44
I confirm its working: my phone was offline immediately with pod method.

The NAS is not offline because it has dos protection enabled. So I have no issues for now.
Thanks for all the support and your time.

**Comment by Taguar258** [comment] 2019-11-14 18:41
I need to thank you, for taking the time reporting the issue and staying patient.

In case I can help you with anything (also in future) issues, suggestions, questions: I am open for anything.

If you want to, you can close the issue.
Reopen it anytime or just open another one.

Thank you and have a nice day.

**Closed** 2019-11-14 20:24 UTC
Labels: bug
